grafana:
  enabled: true

  service:
    type: NodePort
    nodePort: 30300

  adminUser: admin

  persistence:
    enabled: true
    type: pvc
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce
    size: 5Gi

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi


prometheus:
  enabled: true

  prometheusSpec:
    retention: 15d
    retentionSize: 8GB

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce

          resources:
            requests:
              storage: 10Gi

    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 2Gi


alertmanager:
  enabled: true

  alertmanagerSpec:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi


kubeStateMetrics:
  enabled: true


nodeExporter:
  enabled: true